import { Router, type IRouter } from "express";
import healthRouter from "./health";
import menuRouter from "./menu";
import reservationsRouter from "./reservations";
import recipesRouter from "./recipes";
import extractPdfRouter from "./extractPdf";
import extractUrlRouter from "./extractUrl";
import extractImageRouter from "./extractImage";
import extractFridgeRouter from "./extractFridge";
import mealPlansRouter from "./mealPlans";
import uploadImageRouter from "./uploadImage";
import authRouter from "./auth";
import suggestWeekRouter from "./suggestWeek";
import groupsRouter from "./groups";
import cookingLogRouter from "./cookingLog";
import commentsRouter from "./comments";
import notificationsRouter from "./notifications";
import recipeSuggestionsRouter from "./recipeSuggestions";
import mealInvitationsRouter from "./mealInvitations";
import bulkImportRouter from "./bulkImport";
import storageRouter from "./storage";
import pantryRouter from "./pantry";
import kochideeChatRouter from "./kochideeChat";

const router: IRouter = Router();

router.use(healthRouter);
router.use(menuRouter);
router.use(reservationsRouter);
router.use(recipesRouter);
router.use(extractPdfRouter);
router.use(extractUrlRouter);
router.use(extractImageRouter);
router.use(extractFridgeRouter);
router.use(mealPlansRouter);
router.use(uploadImageRouter);
router.use(authRouter);
router.use(suggestWeekRouter);
router.use(groupsRouter);
router.use(cookingLogRouter);
router.use(commentsRouter);
router.use(notificationsRouter);
router.use(recipeSuggestionsRouter);
router.use(mealInvitationsRouter);
router.use(bulkImportRouter);
router.use(storageRouter);
router.use(pantryRouter);
router.use(kochideeChatRouter);

export default router;
